### ISSUE TITLE
Economy deposit/withdraw command not working properlly.

### ISSUE THREAD

**Issue by MG141** [dhvitOP/dyno-clone#11]
I am pasting screenshot of console, will later update with raw paste.

Problems occur with Eocnomy withdraw and deposit command. Even tho the user nas enough money to deposit he is not able to. Output to the discord is "you cannot deposit negative amount".
![Screenshot_20220211_062302_com android chrome_edit_35091823337353](https://user-images.githubusercontent.com/65613737/153543191-38d23386-e464-41d4-a9a3-d56a4d995e88.jpg)
![Screenshot_20220211_062316_com android chrome_edit_35075402947772](https://user-images.githubusercontent.com/65613737/153543195-24b87a1b-a0b9-42d1-8d69-5a4c5cc5a59d.jpg)
![Screenshot_20220211_062329](https://user-images.githubusercontent.com/65613737/153543196-e258e84c-3806-4433-8a1a-1bbe565ec88f.jpg)

**Comment by dhvitish** [comment]
its because of something wrong in your bot
