### ISSUE TITLE
How do I change prefix?

### ISSUE THREAD

**Issue by PRINCE-HERE** [dhvitOP/dyno-clone#3]
I can't Change teh prefix I put the prefix "y." In config.js but then when I used y.help bot didn't respond. Please fox this issue.

**Comment by ShadowGaming100** [comment]
in config.js 
line number 7

> I can't Change teh prefix I put the prefix "y." In config.js but then when I used y.help bot didn't respond. Please fox this issue.

**Comment by PRINCE-HERE** [comment]
Well, nope it doesn't changes the prefix and the bot still uses "." and I clearly said in my last comment that "I put the prefix y. in config.js"

**Comment by dhvitOP** [comment]
Fixed this issue 
It was a database default prefix error which is now fixed changed mainprefix and prefix from config.js both

**Comment by dhvitOP** [comment]
if you have any other issues Please report it

**Comment by PRINCE-HERE** [comment]
Oh sorry I didn't checked that. Thanks for fixing that. I'll let you know if I have any other problems! For now thanks!
