### ISSUE TITLE
Issues with Packages/Dependices 

### ISSUE THREAD

**Issue by DemonWolfFang** [dhvitOP/dyno-clone#8]
There are major issues with packages breaking in the current code. Tar being one of them and I cannot fix it for some odd reason. Also to note ansi-regex has a problem with No Fix Available yet. 

The Discord server invite also does not work on this page.

**Comment by Miracle-bot-creator** [comment]
what is the tar cmd you are using

**Comment by DemonWolfFang** [comment]
Tar is a npm package. Not a command. Not only that when attempting to start the bot `node xp.js` it seems there's an issue finding a sqlite3 package for some reason as well.
